# Generated by Django 5.1.1 on 2024-09-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_delegacia', models.IntegerField()),
                ('data_ocorrencia_bo', models.DateTimeField()),
                ('hora_ocorrencia', models.CharField(max_length=8)),
                ('descr_tipolocal', models.CharField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero_logradouro', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
