# Generated by Django 5.1.1 on 2024-09-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roubos_celulares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roubo',
            old_name='logradouro',
            new_name='rua',
        ),
        migrations.RemoveField(
            model_name='roubo',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='roubo',
            name='descr_tipolocal',
        ),
        migrations.RemoveField(
            model_name='roubo',
            name='id_delegacia',
        ),
        migrations.RemoveField(
            model_name='roubo',
            name='numero_logradouro',
        ),
    ]
