# Generated by Django 5.1.1 on 2024-09-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubos_celulares', '0002_rename_logradouro_roubo_rua_remove_roubo_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roubo',
            name='data_ocorrencia_bo',
        ),
        migrations.AddField(
            model_name='roubo',
            name='data_ocorrencia',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='roubo',
            name='hora_ocorrencia',
            field=models.TimeField(),
        ),
    ]
