# Generated by Django 5.1.1 on 2024-09-25 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubos_celulares', '0003_remove_roubo_data_ocorrencia_bo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roubo',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='roubo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='roubo',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='roubo',
            name='hora_ocorrencia',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roubo',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roubos_celulares.bairro'),
        ),
    ]
