# Generated by Django 5.1.1 on 2024-09-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubos_celulares', '0004_bairro_remove_roubo_cidade_remove_roubo_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bairro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='bairro',
            name='latitude',
        ),
        migrations.AlterField(
            model_name='bairro',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roubo',
            name='data_ocorrencia',
            field=models.DateField(),
        ),
    ]
