# Generated by Django 5.1.1 on 2024-09-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubos_celulares', '0006_bairro_latitude_alter_bairro_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='roubo',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
