# Generated by Django 5.1.1 on 2024-10-01 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubos_celulares', '0007_roubo_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roubo',
            name='hora_ocorrencia',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
