# Generated by Django 5.1.1 on 2024-10-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubos_celulares', '0008_alter_roubo_hora_ocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anonimo', max_length=100)),
                ('email', models.EmailField(default='no-reply@example.com', max_length=254)),
                ('experiencia', models.CharField(choices=[('excelente', 'Excelente'), ('boa', 'Boa'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=20)),
                ('melhorias', models.CharField(choices=[('nada', 'Nada'), ('pequenas', 'Pequenas mudanças'), ('moderadas', 'Mudanças moderadas'), ('grandes', 'Mudanças grandes')], default='nada', max_length=20)),
                ('deixar_informacao', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='roubo',
            name='cidade',
            field=models.CharField(default='Cidade não especificada', max_length=255),
        ),
    ]
